In [1]:
'''
Q-1:Basic of variables
Assigning a value for varible called name and printing type of variable
'''
x="venugopal"
#printing type of variable
print(type(x))
#Create a variable age and assign a value to it. Now, increase its value by 5 and print the new value.
age=20
#printing the value of variable with incrementation of value 5.
print(age+5)

<class 'str'>
25

In [2]:
'''
Q-2:String Manipulation
Given the string s = "PythonIsAmazing",slice the string to obtain “Python”.
'''
#assigning a string to a variable
s = "PythonIsAmazing"
#Slicing the string to obtain "Python"
print(s[0:6])
#Convert the string s to lowercase
print(s.lower())
#For replace “amazing” with “awesome”.
s.replace("Amazing","Awesome")

Python
pythonisamazing

'PythonIsAwesome'

In [4]:
'''
Q-3:Lists
Create a list fruits containing the following fruits: apple, banana, cherry, date.
'''
#Creating a list called fruits
fruits=["apple","banana","cherry","date"]
print(fruits)
#Adding an element called elderberry into the list
fruits.append("elderberry")
print(fruits)
#Removing an element in the list "banana"
fruits.remove("banana")
print(fruits)
#Reversing the list order
fruits.reverse()
print(fruits)

['apple', 'banana', 'cherry', 'date']
['apple', 'banana', 'cherry', 'date', 'elderberry']
['apple', 'cherry', 'date', 'elderberry']
['elderberry', 'date', 'cherry', 'apple']

In [7]:
'''
Q-4:Tuples
Create a tuple coordinates of three values representing x, y, and z coordinates.
'''
x,y,z=4,5,6
coordinates=(x,y,z)
#Unpacking the tupel and assigning the values to another variables
(x_axis,y_axis,z_axis)=coordinates
print(x_axis)
print(y_axis)
print(z_axis)

4
5
6

In [10]:
'''
Q-5:Dictionaries
Create a dictionary student with the following key-value pairs:
•	“name”: [Your Name]
•	“age”: [Your Age]
•	“course”: “Python Programming”
'''
#Creating a Dictionary
dictnory={"name" : "Venugopal","age" : 20, "course" : "Python Programming"}
#Adding a key "grade" and value "A"
dictnory["grade"]="A"
print(dictnory)
#Update the age value to increase by one year.
dictnory["age"]=dictnory["age"]+1
print(dictnory)
#Remove the key “course” from the dictionary.
dictnory.pop("course")
print(dictnory)

{'name': 'Venugopal', 'age': 20, 'course': 'Python Programming', 'grade': 'A'}
{'name': 'Venugopal', 'age': 21, 'course': 'Python Programming', 'grade': 'A'}
{'name': 'Venugopal', 'age': 21, 'grade': 'A'}

In [12]:
'''
Q-6:Sets
Create a set colors containing the following colors: red, green, blue.
'''
colors=["red","green","blue"]
#Adding an element yellow into the set
colors.append("yellow")
print(colors)
#Checking weather an element black is present in the set or not
if "black" in colors:
  print("black is in colors")
else:
  print("black is not in set colors")
#Removing an element "green"
colors.remove("green")
print(colors)

['red', 'green', 'blue', 'yellow']
black is not in set colors
['red', 'blue', 'yellow']

In [19]:
'''
Q-7:Data type Conversions
–	Convert the list fruits into a tuple.
'''
print(fruits)
Tuple=tuple(fruits)
print(Tuple)
#Convert the string s = "12345" into an integer and then into a float.
#creating a string
S="12345"
#changing the data type from string to int
a=int(S)
print(a)
print(type(a))
#changing the data type from int to float
a=float(a)
print(a)
print(type(a))
#creating a list with strings
list_numbers = ["1", "2", "3"]
print(list_numbers)
#creating new_list by changing data types of elements present in list
new_list=[int(x) for x in list_numbers]
print(new_list)

['elderberry', 'date', 'cherry', 'apple']
('elderberry', 'date', 'cherry', 'apple')
12345
<class 'int'>
12345.0
<class 'float'>
['1', '2', '3']
[1, 2, 3]

In [25]:
'''
Q-8:Write a function type_counter that takes a list of different data types and returns a dictionary showing the count of each data type in the list.
'''
#declaring the function type_counter
def type_counter(input_list):
    type_count = {}
    for item in input_list:
        for data_type in [int, str, float, list, tuple]:
            if isinstance(item, data_type):
              #determining the data type of items
                data_type_name = data_type.__name__
                #incrementing the values
                if data_type_name in type_count:
                    type_count[data_type_name] += 1
                else:
                    type_count[data_type_name] = 1
    #returning the result
    return type_count
input_list = [1, "hello", 3.14, [1, 2, 3], (4, 5, 6),1.414]
#function calling
result = type_counter(input_list)
print(result)

{'int': 1, 'str': 1, 'float': 2, 'list': 1, 'tuple': 1}